name: "Release book as PDF"

on:
  push:
    branches:
    - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install required dependencies
        run: |
          sudo apt update -y
          sudo apt install -y texlive texlive-science texlive-plain-generic texlive-pictures texlive-metapost texlive-latex-recommended texlive-latex-base texlive-latex-extra texlive-lang-english texlive-extra-utils texlive-binaries texlive-base texlive-bibtex-extra latexmk biber
      
      - name: Build
        run: |
          make
          
      - name: Read version file
        id: get-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
          
      - name: Fetch release by tag
        id: fetch_release
        uses: pdamianik/release-tag-to-upload-url-action@v1.0.1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.get-version.outputs.content }}
          token: ${{ github.token }}
        continue-on-error: true
                    
      - name: Create release
        id: create_release
        uses: avakar/tag-and-release@v1
        if: steps.fetch_release.outcome != 'success'
        with:
          tag_name: v${{ steps.get-version.outputs.content }}
          release_name: the Magical Zilch book ─ Preview
          body: Preview of the final specification, generated by github actions.
          prerelease: true
          draft: false
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - id: upload_url
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ steps.fetch_release.outcome == 'success' }}
          if_true: ${{ steps.fetch_release.outputs.uploadUrl }}
          if_false: ${{ steps.create_release.outputs.upload_url }} 
        
      - name: Upload pdf book
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload_url.outputs.value }} 
          asset_path: ./magical-zilch-book.pdf
          asset_name: magical-zilch-book.pdf
          asset_content_type: application/pdf
