name: "Release book as PDF"

on:
  push:
    branches:
    - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install required dependencies
        run: |
          sudo apt update -y
          sudo apt install -y texlive
      
      - name: Build
        run: |
          make
          
      - name: Read version file
        id: get-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.get-version.outputs.content }}"
          prerelease: true
          title: "Magical Zilch book - PDF"
          files: |
            *.pdf
