name: "Release book as PDF"

on:
  push:
    branches:
    - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install required dependencies
        run: |
          sudo apt update -y
          sudo apt install -y texlive texlive-science texlive-plain-generic texlive-pictures texlive-metapost texlive-latex-recommended texlive-latex-base texlive-latex-extra texlive-lang-english texlive-extra-utils texlive-binaries texlive-base texlive-bibtex-extra latexmk biber
      
      - name: Build
        run: |
          make
          
      - name: Read version file
        id: get-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-version.outputs.content }}
          name: Magical Zilch book - Preview
          draft: false
          prerelease: true
          body: Preview of the final specification, generated by github actions.
          files: magical-zilch-book.pdf
